In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [3]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
b=np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
a=np.array([1,3,5,6,7])
a

array([1, 3, 5, 6, 7])

In [54]:
def odd(a):
        if a%2==1:
            print(a)
b=np.vectorize(odd)
b(a)

1
1
3
5
7


array([None, None, None, None, None], dtype=object)

In [66]:
import numpy as np
array1 = np.array(a)
array1[array1%2!=0]=-1
array1
# print (np.where(array1==0, -1, array1)) 

array([-1, -1, -1,  6, -1])

In [72]:
q=np.arange(4).reshape(2,2)
q

array([[0, 1],
       [2, 3]])

In [73]:
np.ravel(q)

array([0, 1, 2, 3])

In [87]:
a=np.arange(10).reshape(2,-1)
a
b=np.arange(1,11).reshape(2,-1)
b
np.vstack(a)
np.hstack(b)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.indices([a,b],dtype=int)

TypeError: only integer scalar arrays can be converted to a scalar index

In [91]:
help(np.indices)

Help on function indices in module numpy:

indices(dimensions, dtype=<class 'int'>)
    Return an array representing the indices of a grid.
    
    Compute an array where the subarrays contain index values 0,1,...
    varying only along the corresponding axis.
    
    Parameters
    ----------
    dimensions : sequence of ints
        The shape of the grid.
    dtype : dtype, optional
        Data type of the result.
    
    Returns
    -------
    grid : ndarray
        The array of grid indices,
        ``grid.shape = (len(dimensions),) + tuple(dimensions)``.
    
    See Also
    --------
    mgrid, meshgrid
    
    Notes
    -----
    The output shape is obtained by prepending the number of dimensions
    in front of the tuple of dimensions, i.e. if `dimensions` is a tuple
    ``(r0, ..., rN-1)`` of length ``N``, the output shape is
    ``(N,r0,...,rN-1)``.
    
    The subarrays ``grid[k]`` contains the N-D array of indices along the
    ``k-th`` axis. Explicitly::
    
      

In [102]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
c=len(a)
d=len(b)
for i in a:
    if a[i]==b[i]:
         print(a[i],end=" ")

2 2 2 2 4 